apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-apiserver-proxy
data:
  config-file.yaml: |+
    authorization:
      resourceAttributes:
        apiGroup: registry.cloudrobotics.com
        resource: robots
        subresource: relay-kubernetes-server
        namespace: {{ .Release.Namespace }}
