apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubernetes-relay-server
  labels:
    prometheus: kube-prometheus
spec:
  endpoints:
  - port: http
  selector:
    matchLabels:
      app: kubernetes-relay-server
