apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-relay-relay
imagePullSecrets:
- name: cloud-robotics-images
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-relay-apiserver-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rbac-apiserver-proxy
subjects:
- kind: ServiceAccount
  name: k8s-relay
  namespace: {{ .Release.Namespace }}
{{ if eq .Values.k8s_service_catalog "true" }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kubernetes-relay-server
spec:
  hosts:
{{ if .Values.tenant_domain }}
  - k8s-relay.{{ .Values.tenant_domain }}
{{ else }}
  - {{ .Values.tenant_main_namespace }}-k8s-relay.{{ .Values.domain }}
{{ end }}
  gateways:
  - {{ .Values.tenant_gateway }}
  http:
  - name: kubernetes-relay-server
    match:
    - uri:
        prefix: /apis/core.kubernetes-relay/server
    rewrite:
      uri: /server
    route:
    - destination:
        port:
          number: 8080
        host: kubernetes-relay-server
  - name: kubernetes-relay-client
    match:
    - uri:
        prefix: /apis/core.kubernetes-relay/client
    rewrite:
      uri: /client
    route:
    - destination:
        port:
          number: 8080
        # Via app-router
        host: app-auth-proxy
  - name: kubernetes-relay-oauth
    match:
    - uri:
        prefix: /oauth
    route:
    - destination:
        port:
          number: 8080
        # Via app-router
        host: app-auth-proxy
{{ end }}