apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-relay-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-relay-client
  template:
    metadata:
      labels:
        app: prometheus-relay-client
    spec:
      containers:
      - args:
        - --backend_address
        - {{ .Values.tenant }}-kube-prometheus.{{ .Release.Namespace }}.svc.cluster.local:9090
        - --backend_scheme
        - http
        - --relay_address
        - {{ template "prometheus-domain" . }}
        - --relay_prefix
        - "/apis/core.prometheus-relay"
        - --server_name
        - "{{ .Values.robot.name }}"
        image: "{{ .Values.registry }}/{{ .Values.images.http_relay_client }}"
        name: prometheus-relay-client
        resources:
          requests:
            cpu: 20m
            memory: 100Mi
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
