apiVersion: apps/v1
kind: Deployment
metadata:
  name: cr-syncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cr-syncer
  template:
    metadata:
      labels:
        app: cr-syncer
    spec:
      containers:
      - name: cr-syncer
        args:
        - --remote-server
        - k8s.{{ .Values.domain }}
        - --robot-name
        - "{{ .Values.robot.name }}"
        - --alsologtostderr
        - --verbose=false
        - --listen-address=:8080
        - --namespace
        - "{{ .Values.tenant_main_namespace }}"
        image: "{{ .Values.registry }}/{{ .Values.images.cr_syncer }}"
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 60
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
---
apiVersion: v1
kind: Service
metadata:
  name: cr-syncer
  labels:
    app: cr-syncer
spec:
  selector:
    app: cr-syncer
  ports:
  - name: http
    port: 80
    targetPort: 8080
