// Copyright 2021 The Cloud Robotics Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	missionv1alpha1 "github.com/SAP/cloud-robotics/src/go/pkg/apis/mission/v1alpha1"
	internalinterfaces "github.com/SAP/cloud-robotics/src/go/pkg/client/informers/internalinterfaces"
	v1alpha1 "github.com/SAP/cloud-robotics/src/go/pkg/client/listers/mission/v1alpha1"
	versioned "github.com/SAP/cloud-robotics/src/go/pkg/client/versioned"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MissionInformer provides access to a shared informer and lister for
// Missions.
type MissionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.MissionLister
}

type missionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMissionInformer constructs a new informer for Mission type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMissionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMissionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMissionInformer constructs a new informer for Mission type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMissionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MissionV1alpha1().Missions(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MissionV1alpha1().Missions(namespace).Watch(context.TODO(), options)
			},
		},
		&missionv1alpha1.Mission{},
		resyncPeriod,
		indexers,
	)
}

func (f *missionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMissionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *missionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&missionv1alpha1.Mission{}, f.defaultInformer)
}

func (f *missionInformer) Lister() v1alpha1.MissionLister {
	return v1alpha1.NewMissionLister(f.Informer().GetIndexer())
}
