apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-mesh-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: istio
    kyma-project.io/installation: ""
data:
  kyma_istio_operator: |-
    spec:
      meshConfig:
        accessLogFile: /dev/stdout
        accessLogEncoding: JSON
