domain: "...ondemand.com"
ingress_ip: ""
deploy_environment: "choose one of those GCP/Azure/AWS depending on kyma.cluster"
registry: "ghcr.io/sap/cloud-robotics"
public_registry: "true"
cloud_logging: "false"
stackdriver_logging: "false"
default_gateway: kyma-system/kyma-gateway
k8s_gateway_tls: kyma-gateway-certs
k8s_service_catalog: "false"
