*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 25.04.2019 at 12:25:48
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZEWM_V_TWCR.....................................*
FORM GET_DATA_ZEWM_V_TWCR.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /SCWM/TWCR WHERE
(VIM_WHERETAB) .
    CLEAR ZEWM_V_TWCR .
ZEWM_V_TWCR-MANDT =
/SCWM/TWCR-MANDT .
ZEWM_V_TWCR-LGNUM =
/SCWM/TWCR-LGNUM .
ZEWM_V_TWCR-WCR =
/SCWM/TWCR-WCR .
ZEWM_V_TWCR-ZZ_WCR_ROBOT =
/SCWM/TWCR-ZZ_WCR_ROBOT .
<VIM_TOTAL_STRUC> = ZEWM_V_TWCR.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZEWM_V_TWCR .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZEWM_V_TWCR.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZEWM_V_TWCR-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /SCWM/TWCR WHERE
  LGNUM = ZEWM_V_TWCR-LGNUM AND
  WCR = ZEWM_V_TWCR-WCR .
    IF SY-SUBRC = 0.
    DELETE /SCWM/TWCR .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /SCWM/TWCR WHERE
  LGNUM = ZEWM_V_TWCR-LGNUM AND
  WCR = ZEWM_V_TWCR-WCR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /SCWM/TWCR.
    ENDIF.
/SCWM/TWCR-MANDT =
ZEWM_V_TWCR-MANDT .
/SCWM/TWCR-LGNUM =
ZEWM_V_TWCR-LGNUM .
/SCWM/TWCR-WCR =
ZEWM_V_TWCR-WCR .
/SCWM/TWCR-ZZ_WCR_ROBOT =
ZEWM_V_TWCR-ZZ_WCR_ROBOT .
    IF SY-SUBRC = 0.
    UPDATE /SCWM/TWCR .
    ELSE.
    INSERT /SCWM/TWCR .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZEWM_V_TWCR-UPD_FLAG,
STATUS_ZEWM_V_TWCR-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZEWM_V_TWCR.
  SELECT SINGLE * FROM /SCWM/TWCR WHERE
LGNUM = ZEWM_V_TWCR-LGNUM AND
WCR = ZEWM_V_TWCR-WCR .
ZEWM_V_TWCR-MANDT =
/SCWM/TWCR-MANDT .
ZEWM_V_TWCR-LGNUM =
/SCWM/TWCR-LGNUM .
ZEWM_V_TWCR-WCR =
/SCWM/TWCR-WCR .
ZEWM_V_TWCR-ZZ_WCR_ROBOT =
/SCWM/TWCR-ZZ_WCR_ROBOT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZEWM_V_TWCR USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZEWM_V_TWCR-LGNUM TO
/SCWM/TWCR-LGNUM .
MOVE ZEWM_V_TWCR-WCR TO
/SCWM/TWCR-WCR .
MOVE ZEWM_V_TWCR-MANDT TO
/SCWM/TWCR-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/SCWM/TWCR'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /SCWM/TWCR TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/SCWM/TWCR'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
