apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tenants.config.cloudrobotics.com
  annotations:
    helm.sh/resource-policy: keep
spec:
  group: config.cloudrobotics.com
  names:
    kind: Tenant
    plural: tenants
    singular: tenant
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                tenantDomain:
                  type: string
                  maxLength: 62
            status:
              type: object
              properties:
                robots:
                  type: integer
                robotClusters:
                  type: integer
                gateway:
                  type: string
                tenantDomain:
                  type: string
                  maxLength: 62
                tenantNamespaces:
                  type: array
                  items:
                    type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      lastUpdateTime:
                        type: string
                        format: date-time
                      lastTransitionTime:
                        type: string
                        format: date-time
                      status:
                        type: string
                      type:
                        type: string
                      message:
                        type: string
