apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-basic-conf
data:
  01_sources.conf: |-
    <source>
        @type forward
        bind 0.0.0.0
        port 24224
    </source>

    <source>
        @type http
        port 9880
        bind 0.0.0.0
        <parse>
            @type json
            time_type string
            time_format %iso8601
        </parse>
    </source>

  02_filters.conf: ""

  03_dispatch.conf: ""

  04_outputs.conf: |-
    <match **>
    @type copy
{{ if eq .Values.cloud_logging "true" }}
    <store>
        @type http
        endpoint https://{{ .Values.cloudLoggingFluentdEndpoint }}
        tls_verify_mode peer
        <format>
            @type json
        </format>
        json_array true
        <buffer>
            flush_interval 2s
        </buffer>
        <auth>
            method basic
            username {{ .Values.cloudLoggingFluentdUser }}
            password {{ .Values.cloudLoggingFluentdPassword }}
        </auth>
    </store>
{{ end }}
{{ if eq .Values.stackdriver_logging "true" }}
    <store>
        @type forward
        <server>
            host fluentd-gcp
            port 24224
        </server>
    </store>
{{ end }}
    </match>
