{{ if eq .Values.stackdriver_logging "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-gcp
  labels:
    k8s-app: fluentd-gcp
    version: v3.2.0
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-gcp
      version: v3.2.0
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: fluentd-gcp
        version: v3.2.0
    spec:
      containers:
      - name: fluentd-gcp
        image: gcr.io/stackdriver-agents/stackdriver-logging-agent:1.9.3
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /default-credentials/service-account-file.json
        volumeMounts:
        - name: default-credentials
          mountPath: /default-credentials
        - name: config-volume
          mountPath: /etc/google-fluentd/config.d
        - name: default-config-volume
          mountPath: /etc/google-fluentd/google-fluentd.conf
          subPath: google-fluentd.conf
        ports:
        - name: forwarder
          containerPort: 24224
          protocol: TCP
      volumes:
      - name: default-credentials
        secret:
          secretName: stackdriver-service-account
      - name: config-volume
        configMap:
          name: fluentd-gcp-sources
          defaultMode: 420
      - name: default-config-volume
        configMap:
          name: fluentd-gcp-main-config
          defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: fluentd-gcp
spec:
  type: ClusterIP
  ports:
  - port: 24224
    name: forwarder
    protocol: TCP
    targetPort: forwarder
  selector:
    k8s-app: fluentd-gcp
{{ end }}
