apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-apiserver-proxy
data:
  config-file.yaml: |+
    authorization:
      rewrites:
        byQueryParameter:
          name: "tenant-namespace"
      resourceAttributes:
        apiGroup: registry.cloudrobotics.com
        resource: robots
        subresource: fluentd-proxy
        namespace: "{{ "{{" }} .Value {{ "}}" }}"
