apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-robotics:robot-setup:secrets
  labels:
    config.cloudrobotics.com/aggregate-to-robot-setup: "true"
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs: 
  - create
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-robotics:robot-setup:configmaps
  labels:
    config.cloudrobotics.com/aggregate-to-robot-setup: "true"
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs: 
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-robotics:robot-setup:robots
rules:
- apiGroups:
  - registry.cloudrobotics.com
  resources:
  - robots
  verbs:
  - get
  - list
  - create
  - update
---
# This aggregate role will combine all roles with the given label. This means
# that policy can easily be added for CRDs beyond those listed above.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-robotics:robot-setup:robot-config
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      config.cloudrobotics.com/aggregate-to-robot-setup: "true"
rules: []  # The control plane automatically fills in the rules
