apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-controller
imagePullSecrets:
- name: cloud-robotics-images
---
# TODO: Reduce permissions of tenant controller
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-robotics:tenant-controller:cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
  name: tenant-controller
