{{ if eq .Values.cloud_logging "true" }}
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: cloud-logging-core
spec:
  serviceOfferingName: cloud-logging
  servicePlanName: standard
  parameters: {}
---
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceBinding
metadata:
  name: cloud-logging-core
spec:
  secretName: cloud-logging-core
  serviceInstanceName: cloud-logging-core
  parameters: {}
{{ end }}
