{{ if eq .Values.cloud_logging "true" }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: cloud-logging-core
spec:
  clusterServiceClassExternalName: cloud-logging
  clusterServicePlanExternalName: standard
  parameters: {}
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: cloud-logging-core
spec:
  instanceRef:
    name: cloud-logging-core
  parameters: {}
  secretName: cloud-logging-core
{{ end }}
